include:
  - 'https://gitlab.com/colisweb-open-source/ci-common/raw/v7.8.2/templates/scala.yml'

.opentracing-test:
  extends: .sbt-test
  tags: []

test scala-opentracing:
  extends: .opentracing-test

test scala-opentracing-http4s-test:
  extends: .opentracing-test

test scala-opentracing-amqp:
  extends: .opentracing-test

version:
  extends: .version
  tags: []

publish on bintray:
  extends: .bintray-publish
  tags: []

